export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import HomePage from "@/app/home/_components/HomePage/HomePage";

export default function Home() {
  return <HomePage />
}
