export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import FabricsPage from "@/app/fabrics/_components/FabricsPage/FabricsPage";

export default function Fabrics() {
  return <FabricsPage />
}