export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import GalleryPage from "@/app/gallery/_components/GalleryPage/GalleryPage";

export default function Gallery() {
  return <GalleryPage />
}
