export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import CatalogPage from "@/app/catalog/_components/CatalogPage/CatalogPage";

export default function Catalog() {
  return <CatalogPage />
}