export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ContactsPage from "@/app/contacts/_components/ContactsPage/ContactsPage";

export default function Contacts() {
  return <ContactsPage />
}
